[package]
name = "advent4"
version = "0.1.0"
authors = ["Tanmay Chaudhry <tanmay.chaudhry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.8"
regex = "1"